### PR TITLE
[#139693949] Init maps component

### PR DESCRIPTION
**Pull request by melaniebrgr**
This branch sets up a component that displays a basic Google Map with Markers for every photo that has latitude and longitude information. We might want to consider filtering out for photos that don't have that information.

Beware, I also reorganized and renamed some files or folders – suggestions only. Eventually we'll also want to make a containers folder too, I think.

### CODE REVIEW

**Review by clearlyTHUYDOAN — APPROVED** [review]
Everything looks good. I like the code clean-up and I second moving things into containers. On my local, I have PhotoGallery in a containers folder. Filtering out photos without lat long information would be great. Also, some photos don't contain certain extra detail. Depending on which details we think are important, it may also be good to filter out those without those details too.

**Comment by melaniebrgr** [comment]
Should all state be managed by redux? For example, the PhotoMap component currently holds it's own state that manages InfoWindow display on Marker click – should this be moved to the redux store? 

Relatedly, @AbdellaToronto and @pkanal, are there ever instances when's its OK for component to have it's own state separate from the redux store? I'll add this to next class' GDoc.

**Comment by melaniebrgr** [comment]
On marker click, the ID of the corresponding photo is 'saved' to the redux store. This will let us highlight that photo in the PhotoGallery later.

**Comment by AbdellaToronto** [comment]
A lot of people feel that all state -should- be handled by redux, and there is a lot of merit to that concept - however there are challenges to this, particularly forms - that being said, there are tools to alleviate the challenges that come with these edge cases usually - ie, react-redux-forms

**Comment by AbdellaToronto** [comment]
Looks like the CI was acting up, I think I resolved it however

**Comment by clearlyTHUYDOAN** [comment]
Thanks for resolving it @AbdellaToronto. But it still says, "Some checks haven't completed yet (ci/circleci)". Will it just take time to take effect or are we missing something?

Well, it wont work until a new PR is submitted - or an old PR is resubmitted - so why dont I give that a shot

**Comment by AbdellaToronto** [comment]
Hrmmm, something is weird here - your projects configuration is having issues that aren't happening in other projects - I got the CI to work, but I am getting a unique error when running tests in CI - for now, I think I'll expediate a merge for the sake of moving forward, but I'll be spending some time today/tomorrow trying to figure out why your project is special :)

**Comment by melaniebrgr** [comment]
Thanks Della !!! Hopefully we can get this resolved soon, and let us know if and how we can help.

**Pull request merged**
