### PR TITLE
[CHORE] Add redux form and hook up to search component

### PR DESCRIPTION
**Pull request by pkanal**
This PR hooks up redux form to the search functionality. It will require an `npm install` after rebase.

### CODE REVIEW

**Comment by clearlyTHUYDOAN** [comment]
@pkanal Looks good. I may have to adjust our code a little bit since handleKeyWord was updating a state and that state was being used to show the search word as a title after search fires. I'm assuming I could just grab it from redux-form? Let me know.

**Comment by melaniebrgr** [comment]
@clearlyTHUYDOAN Yeah, exactly the #hashtag title will now come from `state.form.search(?)`. I'm happy to hook it up when I get to integrating this. :)

**Comment by clearlyTHUYDOAN** [comment]
@melaniebrgr Great. I'll approve it for now, squash and merge, and then you can implement that after? I know you want to handle redux-forms ;) @pkanal

**Comment by melaniebrgr** [comment]
Hehe, thanks. You can merge now, or I can do my best to make the changes tonight and we can wait until tonight/tomorrow to merge. Whatever your pref!

**Comment by pkanal** [comment]
@clearlyTHUYDOAN great point! I def missed that. Ill fix it up and push my changes. Awesome catch :)

**Review by melaniebrgr — APPROVED** [review]
Thank you Purvi!!

**Comment by melaniebrgr** [comment]
I'm surprised updates to the combineReducers aren't part of this commit, actually? 
Edit: Nevermind! That's what you meant by it already being in the repo, the formReducer is already combined into the rootReducer.

**Pull request merged**
